ktor:
  application:
    modules:
      - dev.danielslab.shorturl.ApplicationKt.module
  deployment:
    port: 8080
jwt:
  domain: "https://api-s.danielslab.dev"
  audience: "danielslab-short-url"
  realm: "short-url-ktor"
  secret: {}
postgres:
  url: "jdbc:postgresql://localhost/default"
  user: username
  password: password
links:
  default-page-size: 20
  max-page-size: 100
