// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"
)

const createLink = `-- name: CreateLink :one
INSERT INTO links (
  user_id, code, original_url
) VALUES (
  $1, $2, $3
)
RETURNING id, user_id, code, original_url, clicks, created_at, deleted_at
`

type CreateLinkParams struct {
	UserID      int32
	Code        string
	OriginalUrl string
}

func (q *Queries) CreateLink(ctx context.Context, arg CreateLinkParams) (Link, error) {
	row := q.db.QueryRow(ctx, createLink, arg.UserID, arg.Code, arg.OriginalUrl)
	var i Link
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Code,
		&i.OriginalUrl,
		&i.Clicks,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :one
DELETE FROM users
WHERE id = $1
RETURNING id, provider, provider_id, display_name, profile_pic, created_at
`

func (q *Queries) DeleteUser(ctx context.Context, id int32) (User, error) {
	row := q.db.QueryRow(ctx, deleteUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.ProviderID,
		&i.DisplayName,
		&i.ProfilePic,
		&i.CreatedAt,
	)
	return i, err
}

const getLinkByCode = `-- name: GetLinkByCode :one
SELECT id, user_id, code, original_url, clicks, created_at, deleted_at FROM links
WHERE code = $1 AND deleted_at IS NULL
`

func (q *Queries) GetLinkByCode(ctx context.Context, code string) (Link, error) {
	row := q.db.QueryRow(ctx, getLinkByCode, code)
	var i Link
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Code,
		&i.OriginalUrl,
		&i.Clicks,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getLinkByCodeWithDeleted = `-- name: GetLinkByCodeWithDeleted :one
SELECT id, user_id, code, original_url, clicks, created_at, deleted_at FROM links
WHERE code = $1
`

func (q *Queries) GetLinkByCodeWithDeleted(ctx context.Context, code string) (Link, error) {
	row := q.db.QueryRow(ctx, getLinkByCodeWithDeleted, code)
	var i Link
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Code,
		&i.OriginalUrl,
		&i.Clicks,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getLinksByUserID = `-- name: GetLinksByUserID :many
SELECT id, user_id, code, original_url, clicks, created_at, deleted_at FROM links
WHERE user_id = $1 AND deleted_at IS NULL AND id < $2
ORDER BY id DESC
LIMIT $3
`

type GetLinksByUserIDParams struct {
	UserID int32
	ID     int32
	Limit  int32
}

func (q *Queries) GetLinksByUserID(ctx context.Context, arg GetLinksByUserIDParams) ([]Link, error) {
	rows, err := q.db.Query(ctx, getLinksByUserID, arg.UserID, arg.ID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Link
	for rows.Next() {
		var i Link
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Code,
			&i.OriginalUrl,
			&i.Clicks,
			&i.CreatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, provider, provider_id, display_name, profile_pic, created_at FROM users
WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id int32) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.ProviderID,
		&i.DisplayName,
		&i.ProfilePic,
		&i.CreatedAt,
	)
	return i, err
}

const resetDb = `-- name: ResetDb :exec
TRUNCATE users, links RESTART IDENTITY CASCADE
`

func (q *Queries) ResetDb(ctx context.Context) error {
	_, err := q.db.Exec(ctx, resetDb)
	return err
}

const setLinkClicked = `-- name: SetLinkClicked :one
UPDATE links
SET clicks = clicks + 1
WHERE code = $1 AND deleted_at IS NULL
RETURNING clicks
`

func (q *Queries) SetLinkClicked(ctx context.Context, code string) (int32, error) {
	row := q.db.QueryRow(ctx, setLinkClicked, code)
	var clicks int32
	err := row.Scan(&clicks)
	return clicks, err
}

const setLinkDeleted = `-- name: SetLinkDeleted :one
UPDATE links
SET deleted_at = now()
WHERE code = $1 AND user_id = $2 AND deleted_at IS NULL
RETURNING id
`

type SetLinkDeletedParams struct {
	Code   string
	UserID int32
}

func (q *Queries) SetLinkDeleted(ctx context.Context, arg SetLinkDeletedParams) (int32, error) {
	row := q.db.QueryRow(ctx, setLinkDeleted, arg.Code, arg.UserID)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const upsertUser = `-- name: UpsertUser :one
INSERT INTO users (
  provider, provider_id, display_name, profile_pic
) VALUES (
  $1, $2, $3, $4
) ON CONFLICT (provider, provider_id) DO UPDATE
  SET display_name = EXCLUDED.display_name,
      profile_pic = EXCLUDED.profile_pic
RETURNING id, provider, provider_id, display_name, profile_pic, created_at
`

type UpsertUserParams struct {
	Provider    ProviderEnum
	ProviderID  string
	DisplayName *string
	ProfilePic  *string
}

func (q *Queries) UpsertUser(ctx context.Context, arg UpsertUserParams) (User, error) {
	row := q.db.QueryRow(ctx, upsertUser,
		arg.Provider,
		arg.ProviderID,
		arg.DisplayName,
		arg.ProfilePic,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.ProviderID,
		&i.DisplayName,
		&i.ProfilePic,
		&i.CreatedAt,
	)
	return i, err
}
