// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql/driver"
	"fmt"
	"time"
)

type ProviderEnum string

const (
	ProviderEnumGOOGLE ProviderEnum = "GOOGLE"
	ProviderEnumGITHUB ProviderEnum = "GITHUB"
)

func (e *ProviderEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ProviderEnum(s)
	case string:
		*e = ProviderEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for ProviderEnum: %T", src)
	}
	return nil
}

type NullProviderEnum struct {
	ProviderEnum ProviderEnum
	Valid        bool // Valid is true if ProviderEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullProviderEnum) Scan(value interface{}) error {
	if value == nil {
		ns.ProviderEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ProviderEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullProviderEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ProviderEnum), nil
}

type Link struct {
	ID          int32
	UserID      int32
	Code        string
	OriginalUrl string
	Clicks      int32
	CreatedAt   time.Time
	DeletedAt   *time.Time
}

type User struct {
	ID          int32
	Provider    ProviderEnum
	ProviderID  string
	DisplayName *string
	ProfilePic  *string
	CreatedAt   time.Time
}
